### ISSUE TITLE
ruRU localization

### ISSUE THREAD

**Issue by Artur91425** [Road-block/Cartographer#1]
I added ruRU localization in all modules
Updated Libs (with ruRU)
Delete trash from BC version (Herbalism and Mining databases)

[Cartographer.zip](https://github.com/Road-block/Cartographer/files/891051/Cartographer.zip)

**Comment by Road-block** [comment]
Just acknowledging that I've seen the ticket.  
I want to make sure the updated Ace2 libraries cause no issues with other addons before I push your changes.  
Thanks for your work.

**Comment by Road-block** [comment]
https://github.com/Road-block/Cartographer/releases/tag/full_v1.2
