### ISSUE TITLE
Can't open Ironforge and Undercity map on click.

### ISSUE THREAD

**Issue by CHERNO94** [Road-block/Cartographer#10]
Basically, the title. I can't open the map of Ironforge by clicking on its area on location map. This is also true for Undercity.

**Comment by Hiethen** [comment]
I previously ran into this issue as well. https://github.com/slowtorta/turtlewow-bug-tracker/issues/2482
Unfortunately, its a bug in the original client.

**Comment by CHERNO94** [comment]
Thanks for the answer! Did not know that.
