### ISSUE TITLE
Compatibility with custom vanilla maps

### ISSUE THREAD

**Issue by Haaxor1689** [Road-block/Cartographer#11]
Currently Cartographer does not work correctly with custom world map data. I could create a PR that would solve this issue without affecting vanilla players, just want a "go ahead" from the author if possible. :)

![image](https://user-images.githubusercontent.com/25706343/205461526-84eb8d00-3c4b-4911-b3ac-06438fa5591e.png)

**Comment by Road-block** [comment]
I'm not the original author of this mod I just found a relevant version and fixed some outstanding issues to make it working on 1.12.x vanilla client few years back.

I'm no longer playing on that client but I'm happy to accept PRs if this is still getting use.

**Comment by Haaxor1689** [comment]
I was trying to fix this issue but even though I comment out the error alert in `AceLocale.prototype:GetReverseTranslation` and return the original text so it shows untranslated text instead of nothing, for some reason it still logs the same error into console and I can't find where that error is logged from. Here is the only change I made. 
![image](https://user-images.githubusercontent.com/25706343/205592486-c33300a4-7eba-4f03-a952-b0a2cde78c1a.png)

**Comment by Road-block** [comment]
Libraries are shared code that only remains in memory once.

What that means is that if there's other addons embedding Ace/AceLocale you'd need to do the same replacement in all.
The other option is to up the minor version of the library instance you edited so it's the one that remains in memory.

None of those are "proper" fixes honestly 😃 

It would be best to add the missing zones to Babble-Zone and up the minor in that instead.

**Comment by Haaxor1689** [comment]
So I've added the custom zones and bumped the babble zone version. Want me to open PR or keep it separate and direct turtle wow players to my fork?

**Comment by Road-block** [comment]
Second option probably best 😃

**Comment by Road-block** [comment]
> So I've added the custom zones and bumped the babble zone version. Want me to open PR or keep it separate and direct turtle wow players to my fork?

Hey I replied before taking a look at your changes. 
I should have clarified what I meant by upping the minor version.

You didn't need to change BabbleZone to 2.3.
The minor version far as the library is concerned is this [Babble-Zone-2.3.lua:L13](https://github.com/Haaxor1689/Cartographer/blob/92e8fffec24f011432fd230d1046de3e9e5dab52/Libs/Babble-Zone-2.3/Babble-Zone-2.3.lua#L13)

You don't need to rename the library folder or change the major (I know .2 based on semantic versioning concept would count as minor but it's not in this case)

You just need to up the `17779` revision number to a higher number.

**Comment by Haaxor1689** [comment]
ooh I see :D btw this will also cause other addons that use Babble-Zone load the updated version as well?

**Comment by Road-block** [comment]
That's correct
