### ISSUE TITLE
superfluous line

### ISSUE THREAD

**Issue by Artur91425** [Road-block/Cartographer#2]
Sorry please, I did not notice at once.

can you delete superfluous line in Cartographer_Mining\addon.lua?
line 52: 	["Thoriums"] = "ториевая",
this line сauses an error:
https://pp.userapi.com/c836539/v836539208/2e8f2/WNZQC0WaJX8.jpg

**Comment by Road-block** [comment]
https://github.com/Road-block/Cartographer_Mining/commit/09aa2fe337fd500257723c121830bb5e45360e53

Full package updated as well.
