### ISSUE TITLE
Fix error

### ISSUE THREAD

**Issue by Artur91425** [Road-block/Cartographer#3]
Fix this please:
![ymj1u-gnqeo](https://cloud.githubusercontent.com/assets/24303693/26286915/7afe9fce-3e78-11e7-83f6-9f1c5c63e9a5.jpg)

Cartographer_Mining\addon.lua :
107 line:
local mod = Cartographer:NewModule(bs["Mining"], "AceConsole-2.0", "AceEvent-2.0")
need change to:
local mod = Cartographer:NewModule("Mining", "AceConsole-2.0", "AceEvent-2.0")
245 line:
Cartographer.options.args[bs["Mining"]] = {
need change to:
Cartographer.options.args.Mining = {
253 line:
AceLibrary("AceConsole-2.0"):InjectAceOptionsTable(self, Cartographer.options.args[bs["Mining"]])
need change to:
AceLibrary("AceConsole-2.0"):InjectAceOptionsTable(self, Cartographer.options.args.Mining)

Cartographer_Herbalism\addon.lua :
469 line:
Cartographer.options.args[gsub(bs["Herbalism"], " ", "")] = {
need change to:
Cartographer.options.args.Herbalism = {
476 line:
AceLibrary("AceConsole-2.0"):InjectAceOptionsTable(self, Cartographer.options.args[gsub(bs["Herbalism"], " ", "")])
need change to:
AceLibrary("AceConsole-2.0"):InjectAceOptionsTable(self, Cartographer.options.args.Herbalism)

**Comment by Road-block** [comment]
I'll take a look tomorrow.

**Comment by Road-block** [comment]
Should be fixed with [8ebfe4cdce1](https://github.com/Road-block/Cartographer_Mining/commit/79363592a61d8bd52b577556b68b08ebfe4cdce1)
Full package zip updated as well [here](https://github.com/Road-block/Cartographer/releases/latest)

**Comment by Road-block** [comment]
https://github.com/Road-block/Cartographer/releases/latest
